version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
    restart: always
    command: --ISCAgent false
    ports:
      - 41773:1972
      - 42773:52773
      - 53773
    volumes:
      - ./:/home/irisowner/dev
      - ./src/csp:/usr/irissys/mgr/csp/irisapp
