# This is a basic workflow to help you get started with Actions

name: ZPM test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [ workflow_dispatch ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    env:
      package: Samples-Aviation
      container_image: intersystemsdc/iris-community:2020.4.0.524.0-zpm
      instance: iris
    
    # something wrong here?
    # outputs:
    #  zpm-log: ${{ steps.zpm-test.outputs.version }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Start ZPM-enabled Container
        id: container-start
        run: |
          # Run InterSystems IRIS instance
          docker pull $container_image
          docker run -d --name $instance -v $GITHUB_WORKSPACE:/source $container_image
          echo halt > wait
          # build test script
          # docker exec $instance bash -c "printf 'zpm\nload /source\nquit\nhalt\n' > test-zpm.script"
          # docker exec my-iris bash -c "iris session iris < test-zpm3.script"
          # Wait for instance to be ready
          until docker exec $instance iris session $instance < wait; do sleep 1; done
          
      - name: Test ZPM installation
        id: zpm-test
        run: |
          echo "zpm \"load /source\":1:1" > load-zpm
          docker exec --interactive $instance iris session $instance -B < load-zpm
